# Generated by Django 4.2.3 on 2023-07-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Labour_Broker", "0002_alter_labour_data_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labour_data",
            name="type",
            field=models.CharField(
                choices=[
                    ("default", "Select worker type"),
                    ("agriculture", "Agriculture"),
                    ("construction", "Construction"),
                ],
                default="default",
                max_length=100,
            ),
        ),
    ]
