# Generated by Django 4.2.3 on 2023-07-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Labour_Broker", "0003_alter_labour_data_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="labour_data",
            name="contact",
            field=models.IntegerField(null=True),
        ),
    ]
