# Generated by Django 4.2.3 on 2023-07-17 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Labour_Broker", "0005_labour_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labour_type",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
