# Generated by Django 4.2.3 on 2023-07-19 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Labour_Broker", "0007_labour_data_other_details_labour_data_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labour_data",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
