# Generated by Django 4.2.3 on 2023-07-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Labour_Broker", "0008_alter_labour_data_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="labour_data",
            name="other_type",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="labour_data",
            name="type",
            field=models.CharField(
                choices=[
                    ("default", "Select worker type"),
                    ("agriculture", "Agriculture"),
                    ("construction", "Construction"),
                    ("Houseworks", "Houseworks"),
                    ("textile", "textile"),
                    ("machinary", "machinary"),
                ],
                default="default",
                max_length=100,
            ),
        ),
    ]
