# Generated by Django 4.2.3 on 2023-07-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Labour_Broker", "0009_labour_data_other_type_alter_labour_data_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labour_data",
            name="type",
            field=models.CharField(
                choices=[
                    ("agriculture", "Agriculture"),
                    ("construction", "Construction"),
                    ("Houseworks", "Houseworks"),
                    ("textile", "textile"),
                    ("machinary", "machinary"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
