# Generated by Django 4.2.3 on 2023-07-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Labour_Broker", "0011_alter_labour_data_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labour_data",
            name="other_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="labour_data",
            name="other_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="labour_data",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agriculture", "Agriculture"),
                    ("construction", "Construction"),
                    ("Houseworks", "Houseworks"),
                    ("textile", "textile"),
                    ("machinary", "machinary"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
