# Generated by Django 4.2.3 on 2023-07-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Labour_Broker", "0012_alter_labour_data_other_details_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labour_data",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select worker type"),
                    ("Agriculture", "Agriculture"),
                    ("Construction", "Construction"),
                    ("Houseworks", "Houseworks"),
                    ("Textile", "textile"),
                    ("Machinary", "machinary"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
